rule all:
    input:
        "final_reads/reads_coi_Sample_name.fastq",
        "data/interim/output_plot_Sample_name"

rule check_quality:
    input:
        fastq="Data/fastq/calvin_5A1.fastq"
    output:
        directory("data/interim/output_plot_Sample_name")
    conda:
        "envs/qc.yaml"
    log:
        "logs/check_quality.log"
    shell:
        """
        NanoPlot --fastq {input.fastq} -o {output} 2> {log}
        """

rule filter_reads:
    input:
        fastq="Data/fastq/calvin_5A1.fastq"
    output:
        "coi_reads_length_Sample_name.fastq"
    conda:
        "envs/qc.yaml"
    log:
        "logs/filter_reads.log"
    shell:
        """
        NanoFilt {input.fastq} -l 345 --maxlength 500 -q 10 > {output} 2> {log}
        """

rule cutadapt_forward:
    input:
        "coi_reads_length_Sample_name.fastq"
    output:
        "cut_primers/coi_for_Sample_name.fastq"
    conda:
        "envs/qc.yaml"
    log:
        "logs/cutadapt_forward.log"
    shell:
        """
        cutadapt -g GGWACWRGWTGRACWNTNTAYCCYCC...TGRTTYTTYGGNCAYCCNGARGTNTA \
        -o {output} {input} -e 0.2 -m 293 -M 333 --discard-untrimmed > {log} 2>&1
        """

rule cutadapt_reverse:
    input:
        "coi_reads_length_Sample_name.fastq"
    output:
        "cut_primers/coi_rev_Sample_name.fastq"
    conda:
        "envs/qc.yaml"
    log:
        "logs/cutadapt_reverse.log"
    shell:
        """
        cutadapt -g TANACYTCNGGRTGNCCRAARAAYCA...GGRGGRTANANWGTYCAWCYWGTWCC \
        -o {output} {input} -e 0.2 -m 293 -M 333 --discard-untrimmed > {log} 2>&1
        """

rule concatenate_reads:
    input:
        forward="cut_primers/coi_for_Sample_name.fastq",
        reverse_reads="cut_primers/coi_rev_Sample_name.fastq"
    output:
        "final_reads/reads_coi_Sample_name.fastq"
    shell:
        """
        cat {input.forward} {input.reverse_reads} > {output}
        """